on: push
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build docker images
        run: docker build --tag local - < .devcontainer/Dockerfile
      - name: Run tests
        run: docker run -v $PWD:/srv -w/srv local make test
